---
- hosts: localhost
  connection: local

  vars_files:
     - vars/main.yml

  tasks:

     # Ansible setup
     - name: Ensure Ansible downloads directory exists
       file: path={{ item }} state=directory
       with_items:
          - ~/bin/
          - ~/proj
          - ~/.lein
          - ~/.pip
          - ~/.tmux/plugins/
          - "{{ downloads }}"

     - name: Check oh-my-zsh installed
       stat: path=~/.oh-my-zsh
       register: oh_my_zsh_dir

     - name: Install oh-my-zsh
       shell: sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
       when: oh_my_zsh_dir.stat.exists == false

     - name: Clone dotfiles
       git: repo={{ dotfiles_repo }}
            dest={{ dotfiles_repo_local_destination }}

     - name: Link dotfiles
       file: path={{ item.dst }} src={{ dotfiles_repo_local_destination }}/{{ item.src }} state=link
       with_items: "{{ dotfiles_files }}"
       
     - name: Link Emacs application
       command: brew linkapps emacs creates=/Applications/Emacs.app

     - name: Install spacemacs
       git: repo=https://github.com/syl20bnr/spacemacs
            dest=~/.emacs.d

     - name: Install Leiningen
       get_url: url=https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein dest=~/bin/lein mode=755

     - name: Install Tmux Plugin Manager
       git: repo=https://github.com/tmux-plugins/tpm
            dest=~/.tmux/plugins/tpm

     - name: Initialize the state of OPAM (OCaml pacakge manager)
       command: opam init creates=~/.opam
     - name: Install OCaml packages
       command: opam install --build-doc --strict --quiet --yes {{ item }}
       with_items:
         - merlin
         - utop
         - ocp-indent

     - include: tasks/vim.yml
     - include: tasks/python.yml
     - include: tasks/osx.yml
     # - include: tasks/install_fonts.yml
     # - include: tasks/install_ua_spellchecker.yml
     - include: tasks/homebrew.yml
