# --------------------- GO tools
- name: Install gocode
  command: go get -u -v github.com/nsf/gocode

- name: Install godef
  command: go get -u -v github.com/rogpeppe/godef

- name: Install go-oracle
  command: go get -u -v golang.org/x/tools/cmd/oracle